services:

  mysql:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: steam_pipeline

    ports:
      - "3307:3306"
    
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  pipeline:
    build: .

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env.docker

  dashboard:
    build: .

    command: streamlit run src/dashboard.py --server.address=0.0.0.0 --server.port=8501

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env.docker

    ports:
      - "8501:8501"
