services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${PIPELINE_DB_USER}
      MYSQL_PASSWORD: ${PIPELINE_DB_PASSWORD}
      DASHBOARD_DB_USER: ${DASHBOARD_DB_USER}
      DASHBOARD_DB_PASSWORD: ${DASHBOARD_DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  migrate:
    image: flyway/flyway:13.4.0-alpine
    command: migrate

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      FLYWAY_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false"
      FLYWAY_USER: ${PIPELINE_DB_USER}
      FLYWAY_PASSWORD: ${PIPELINE_DB_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 10
      FLYWAY_LOCATIONS: filesystem:/flyway/migrations

    volumes:
      - ./db/migrations:/flyway/migrations:ro

  pipeline:
    build: .
    image: steam-data-pipeline-app:local

    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${PIPELINE_DB_USER}
      MYSQL_PASSWORD: ${PIPELINE_DB_PASSWORD}
      STEAMSPY_MODE: ${STEAMSPY_MODE:-all}
      STEAMSPY_PAGE: ${STEAMSPY_PAGE:-0}

  dashboard:
    build: .
    image: steam-data-pipeline-app:local
    restart: unless-stopped

    command: >
      streamlit run src/dashboard.py
      --server.address=0.0.0.0
      --server.port=8501
      --browser.gatherUsageStats=false
    depends_on:
      mysql:
        condition: service_healthy
      pipeline:
        condition: service_completed_successfully

    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DASHBOARD_DB_USER}
      MYSQL_PASSWORD: ${DASHBOARD_DB_PASSWORD}

    ports:
      - "127.0.0.1:8501:8501"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8501/_stcore/health', timeout=2)"
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  mysql_data: